# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oip_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(Form)
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.header)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.myAddrLineEdit = QtWidgets.QLineEdit(self.header)
        self.myAddrLineEdit.setObjectName("myAddrLineEdit")
        self.horizontalLayout.addWidget(self.myAddrLineEdit)
        self.setMyAddress = QtWidgets.QPushButton(self.header)
        self.setMyAddress.setObjectName("setMyAddress")
        self.horizontalLayout.addWidget(self.setMyAddress)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.header)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.devieAddrLineEdit = QtWidgets.QLineEdit(self.header)
        self.devieAddrLineEdit.setObjectName("devieAddrLineEdit")
        self.horizontalLayout.addWidget(self.devieAddrLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.syncDIDPushButton = QtWidgets.QPushButton(self.header)
        self.syncDIDPushButton.setObjectName("syncDIDPushButton")
        self.horizontalLayout.addWidget(self.syncDIDPushButton)
        self.verticalLayout.addWidget(self.header)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.basicTab = QtWidgets.QWidget()
        self.basicTab.setObjectName("basicTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.basicTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.operationGroup = QtWidgets.QGroupBox(self.basicTab)
        self.operationGroup.setObjectName("operationGroup")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.operationGroup)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cmdComboBox = QtWidgets.QComboBox(self.operationGroup)
        self.cmdComboBox.setObjectName("cmdComboBox")
        self.horizontalLayout_4.addWidget(self.cmdComboBox)
        self.typeComboBox = QtWidgets.QComboBox(self.operationGroup)
        self.typeComboBox.setMinimumSize(QtCore.QSize(30, 0))
        self.typeComboBox.setObjectName("typeComboBox")
        self.horizontalLayout_4.addWidget(self.typeComboBox)
        self.didLabel = QtWidgets.QLabel(self.operationGroup)
        self.didLabel.setObjectName("didLabel")
        self.horizontalLayout_4.addWidget(self.didLabel)
        self.didcomboBox = QtWidgets.QComboBox(self.operationGroup)
        self.didcomboBox.setEnabled(True)
        self.didcomboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.didcomboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.didcomboBox.setEditable(True)
        self.didcomboBox.setObjectName("didcomboBox")
        self.horizontalLayout_4.addWidget(self.didcomboBox)
        self.sendPushButton = QtWidgets.QPushButton(self.operationGroup)
        self.sendPushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sendPushButton.setObjectName("sendPushButton")
        self.horizontalLayout_4.addWidget(self.sendPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.operationGroup)
        self.dataGroup = QtWidgets.QGroupBox(self.basicTab)
        self.dataGroup.setMinimumSize(QtCore.QSize(0, 80))
        self.dataGroup.setObjectName("dataGroup")
        self.verticalLayout_2.addWidget(self.dataGroup)
        self.tabWidget.addTab(self.basicTab, "")
        self.imageTab = QtWidgets.QWidget()
        self.imageTab.setObjectName("imageTab")
        self.layoutWidget = QtWidgets.QWidget(self.imageTab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 403, 242))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageLabel = QtWidgets.QLabel(self.layoutWidget)
        self.imageLabel.setMinimumSize(QtCore.QSize(320, 240))
        self.imageLabel.setStyleSheet("background:rgb(0, 255, 0)")
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout_2.addWidget(self.imageLabel)
        self.readImagePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.readImagePushButton.setObjectName("readImagePushButton")
        self.horizontalLayout_2.addWidget(self.readImagePushButton)
        self.tabWidget.addTab(self.imageTab, "")
        self.updateTab = QtWidgets.QWidget()
        self.updateTab.setObjectName("updateTab")
        self.tabWidget.addTab(self.updateTab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "抄控器地址"))
        self.myAddrLineEdit.setText(_translate("Form", "1"))
        self.setMyAddress.setText(_translate("Form", "设置"))
        self.label_2.setText(_translate("Form", "设备地址"))
        self.syncDIDPushButton.setText(_translate("Form", "刷新did列表"))
        self.operationGroup.setTitle(_translate("Form", "操作"))
        self.didLabel.setText(_translate("Form", "DID"))
        self.sendPushButton.setText(_translate("Form", "发送"))
        self.dataGroup.setTitle(_translate("Form", "回复"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.basicTab), _translate("Form", "基本配置"))
        self.imageLabel.setText(_translate("Form", "TextLabel"))
        self.readImagePushButton.setText(_translate("Form", "readImage"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.imageTab), _translate("Form", "图像读取"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.updateTab), _translate("Form", "升级"))
