# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'protocol_master_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(964, 645)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter_h = QtGui.QSplitter(self.centralWidget)
        self.splitter_h.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_h.setOpaqueResize(True)
        self.splitter_h.setHandleWidth(5)
        self.splitter_h.setChildrenCollapsible(False)
        self.splitter_h.setObjectName(_fromUtf8("splitter_h"))
        self.treeWidget = QtGui.QTreeWidget(self.splitter_h)
        self.treeWidget.setEnabled(True)
        self.treeWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.splitter_v = QtGui.QSplitter(self.splitter_h)
        self.splitter_v.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter_v.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter_v.setMidLineWidth(1)
        self.splitter_v.setOrientation(QtCore.Qt.Vertical)
        self.splitter_v.setObjectName(_fromUtf8("splitter_v"))
        self.tabWidget = QtGui.QTabWidget(self.splitter_v)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabFrame = QtGui.QWidget()
        self.tabFrame.setObjectName(_fromUtf8("tabFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tabFrame)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tableWidgetFrame = QtGui.QTableWidget(self.tabFrame)
        self.tableWidgetFrame.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidgetFrame.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetFrame.setAlternatingRowColors(True)
        self.tableWidgetFrame.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidgetFrame.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetFrame.setObjectName(_fromUtf8("tableWidgetFrame"))
        self.tableWidgetFrame.setColumnCount(3)
        self.tableWidgetFrame.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetFrame.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetFrame.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetFrame.setHorizontalHeaderItem(2, item)
        self.tableWidgetFrame.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetFrame.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetFrame.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableWidgetFrame)
        self.textBrowserFrameInfo = QtGui.QTextBrowser(self.tabFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setKerning(False)
        self.textBrowserFrameInfo.setFont(font)
        self.textBrowserFrameInfo.setObjectName(_fromUtf8("textBrowserFrameInfo"))
        self.horizontalLayout.addWidget(self.textBrowserFrameInfo)
        self.tabWidget.addTab(self.tabFrame, _fromUtf8(""))
        self.tabLog = QtGui.QWidget()
        self.tabLog.setObjectName(_fromUtf8("tabLog"))
        self.gridLayout = QtGui.QGridLayout(self.tabLog)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textBrowser = QtGui.QTextBrowser(self.tabLog)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabLog, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.splitter_h, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 964, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuSet = QtGui.QMenu(self.menuBar)
        self.menuSet.setObjectName(_fromUtf8("menuSet"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuDevice = QtGui.QMenu(self.menuBar)
        self.menuDevice.setObjectName(_fromUtf8("menuDevice"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolbar = QtGui.QToolBar(MainWindow)
        self.toolbar.setObjectName(_fromUtf8("toolbar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.openDatabaseAction = QtGui.QAction(MainWindow)
        self.openDatabaseAction.setObjectName(_fromUtf8("openDatabaseAction"))
        self.exportDatabaseAction = QtGui.QAction(MainWindow)
        self.exportDatabaseAction.setObjectName(_fromUtf8("exportDatabaseAction"))
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.menuBar.addAction(self.menuSet.menuAction())
        self.menuBar.addAction(self.menuDevice.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolbar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.treeWidget, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), MainWindow.clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "智能硬件测试工具", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "APP名称", None))
        item = self.tableWidgetFrame.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "时间", None))
        item = self.tableWidgetFrame.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "标记", None))
        item = self.tableWidgetFrame.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "数据", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFrame), _translate("MainWindow", "帧信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLog), _translate("MainWindow", "日志", None))
        self.menuSet.setTitle(_translate("MainWindow", "设置", None))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助", None))
        self.menuDevice.setTitle(_translate("MainWindow", "设备", None))
        self.openDatabaseAction.setText(_translate("MainWindow", "open", None))
        self.exportDatabaseAction.setText(_translate("MainWindow", "export", None))
        self.action.setText(_translate("MainWindow", "串口", None))

