# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'protocol_master_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 583)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.leftTreeWidget = QtWidgets.QTreeWidget(self.splitter)
        self.leftTreeWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftTreeWidget.sizePolicy().hasHeightForWidth())
        self.leftTreeWidget.setSizePolicy(sizePolicy)
        self.leftTreeWidget.setMinimumSize(QtCore.QSize(50, 50))
        self.leftTreeWidget.setMaximumSize(QtCore.QSize(200, 111111))
        self.leftTreeWidget.setBaseSize(QtCore.QSize(0, 0))
        self.leftTreeWidget.setAutoScroll(True)
        self.leftTreeWidget.setObjectName("leftTreeWidget")
        self.leftTreeWidget.header().setDefaultSectionSize(120)
        self.leftTreeWidget.header().setMinimumSectionSize(40)
        self.rightSpace = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightSpace.sizePolicy().hasHeightForWidth())
        self.rightSpace.setSizePolicy(sizePolicy)
        self.rightSpace.setStyleSheet("")
        self.rightSpace.setObjectName("rightSpace")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rightSpace)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.rightSpace)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.upper = QtWidgets.QWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.upper.sizePolicy().hasHeightForWidth())
        self.upper.setSizePolicy(sizePolicy)
        self.upper.setMinimumSize(QtCore.QSize(0, 150))
        self.upper.setStyleSheet("")
        self.upper.setObjectName("upper")
        self.lower = QtWidgets.QWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.lower.sizePolicy().hasHeightForWidth())
        self.lower.setSizePolicy(sizePolicy)
        self.lower.setMinimumSize(QtCore.QSize(0, 120))
        self.lower.setStyleSheet("")
        self.lower.setObjectName("lower")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.lower)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.lower)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.tabWidget.setObjectName("tabWidget")
        self.tablFrame = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablFrame.sizePolicy().hasHeightForWidth())
        self.tablFrame.setSizePolicy(sizePolicy)
        self.tablFrame.setMinimumSize(QtCore.QSize(0, 60))
        self.tablFrame.setObjectName("tablFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tablFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.tablFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setMinimumSize(QtCore.QSize(0, 100))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.tableWidgetFrame = QtWidgets.QTableWidget(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetFrame.sizePolicy().hasHeightForWidth())
        self.tableWidgetFrame.setSizePolicy(sizePolicy)
        self.tableWidgetFrame.setMinimumSize(QtCore.QSize(0, 120))
        self.tableWidgetFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidgetFrame.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidgetFrame.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetFrame.setAlternatingRowColors(True)
        self.tableWidgetFrame.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidgetFrame.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetFrame.setWordWrap(False)
        self.tableWidgetFrame.setCornerButtonEnabled(False)
        self.tableWidgetFrame.setRowCount(0)
        self.tableWidgetFrame.setObjectName("tableWidgetFrame")
        self.tableWidgetFrame.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFrame.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFrame.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFrame.setHorizontalHeaderItem(2, item)
        self.tableWidgetFrame.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetFrame.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetFrame.verticalHeader().setVisible(False)
        self.textBrowserFrameInfo = QtWidgets.QTextBrowser(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserFrameInfo.sizePolicy().hasHeightForWidth())
        self.textBrowserFrameInfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setKerning(False)
        self.textBrowserFrameInfo.setFont(font)
        self.textBrowserFrameInfo.setObjectName("textBrowserFrameInfo")
        self.horizontalLayout.addWidget(self.splitter_3)
        self.tabWidget.addTab(self.tablFrame, "")
        self.tabLog = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabLog.sizePolicy().hasHeightForWidth())
        self.tabLog.setSizePolicy(sizePolicy)
        self.tabLog.setObjectName("tabLog")
        self.tabWidget.addTab(self.tabLog, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.splitter_2)
        self.horizontalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 834, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuSet = QtWidgets.QMenu(self.menuBar)
        self.menuSet.setObjectName("menuSet")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuDevice = QtWidgets.QMenu(self.menuBar)
        self.menuDevice.setObjectName("menuDevice")
        MainWindow.setMenuBar(self.menuBar)
        self.toolbar = QtWidgets.QToolBar(MainWindow)
        self.toolbar.setObjectName("toolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuSet.menuAction())
        self.menuBar.addAction(self.menuDevice.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolbar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.leftTreeWidget.clicked['QModelIndex'].connect(MainWindow.plug_index_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智能硬件测试工具"))
        self.leftTreeWidget.headerItem().setText(0, _translate("MainWindow", "APP名称"))
        item = self.tableWidgetFrame.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "时间"))
        item = self.tableWidgetFrame.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "标记"))
        item = self.tableWidgetFrame.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tablFrame), _translate("MainWindow", "帧信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLog), _translate("MainWindow", "日志"))
        self.menuSet.setTitle(_translate("MainWindow", "设置"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.menuDevice.setTitle(_translate("MainWindow", "设备"))
